add a function (lineheight and fontsize can be change)
cocos-creator-packages/console pull request #38
Opened 2017-09-20 02:36 UTC by DHLXK

加了两个select控件，分别是fontsize和lineheight @VisualSJ

2017-09-20 09:11 UTC, VisualSJ commented
另外，其实 console 的部分元素不是居中的，看到这些问题可以顺带稍微移动一下。

2017-09-21 03:56 UTC, DHLXK commented
将fontsize和lineheight加入到了profiles中，调整了console的工具栏，可以伸缩成两行。 @VisualSJ

2017-09-21 06:13 UTC, VisualSJ commented
![1505974225942](https://user-images.githubusercontent.com/7113508/30681218-062540bc-9ed7-11e7-892a-24d460172b2f.jpg)

```
Editor.error(new Error('error'));
```
这个打印的错误会有个下拉菜单，展开后的数据并没有设置到字号~

2017-09-21 06:16 UTC, VisualSJ requested changes

2017-09-21 06:16 UTC, VisualSJ commented on package.json
> +    "profiles": {
https://github.com/cocos-creator/fireball/pull/6373

这个你需要更新一下 creator 主仓库， profiles 已经挪到 package 上了，不是在 panels 里面了。

2017-09-21 06:16 UTC, VisualSJ commented on panel/manager.js
> +            var itemHeight = exports.itemHeight;
模块顶部定义了一个 itemHeight 局部变量，这边没必要在创建一个局部变量。

2017-09-22 07:33 UTC, DHLXK commented
@VisualSJ 错误信息的下拉框一样可以改变字号和行高

2017-09-25 01:28 UTC, VisualSJ approved these changes

2017-10-13 09:16 UTC, merged